
name: CI

on:
  push:
    branches:
      - main
      - release
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
      - release
    paths-ignore:
      - '**.md'

jobs:
  ci:
    uses: codenamephp/workflows.php/main/ci.yml@main
